### ISSUE TITLE
'KeyboardView' does not have a member named 'addKey' (x5)

### ISSUE THREAD

**Issue by revblaze** [Brimizer/Slidden#1]
![Run Test](https://cloud.githubusercontent.com/assets/1476332/4367355/cac21876-42d4-11e4-9cc6-980c128daf98.png)

**Comment by Brimizer** [comment]
Thanks for logging that. I'm in the process of moving the function to be delegate methods to improve control over the views and improve speed. Will update when I can.

**Comment by pannous** [comment]
In the meantime you (forkers) can switch from private to public:
    private func addKey(key: KeyboardKeyView, row: Int) {
    public func addKey(key: KeyboardKeyView, row: Int) {
